// Shared inline styles for consistent theming across all pages
export const theme = {
  colors: {
    primary: "#0284c7",
    primaryHover: "#0369a1",
    secondary: "#e0f2fe",
    secondaryHover: "#bae6fd",
    background: "#f0f9ff",
    border: "#bae6fd",
    text: "#1e293b",
    textMuted: "#64748b",
    error: "#ef4444",
    errorBg: "#fee2e2",
    success: "#22c55e",
    lightBlue: "#f0f9ff",
    cardBg: "#ffffff",
  },
  font: {
    family: "system-ui, -apple-system, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif",
  },
  spacing: {
    xs: "4px",
    sm: "8px",
    md: "16px",
    lg: "24px",
    xl: "32px",
  },
  borderRadius: {
    sm: "6px",
    md: "8px",
    lg: "12px",
  },
};

export const commonStyles = {
  pageContainer: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "flex-start",
    minHeight: "100vh",
    width: "100%",
    padding: theme.spacing.lg,
    background: "linear-gradient(135deg, #f0f9ff 0%, #e0f2fe 50%, #f0f9ff 100%)",
    fontFamily: theme.font.family,
    direction: "rtl",
  },
  contentWrapper: {
    width: "100%",
    maxWidth: "1400px",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "flex-start",
    gap: theme.spacing.lg,
  },
  card: {
    width: "100%",
    backgroundColor: theme.colors.cardBg,
    border: "1px solid " + theme.colors.border,
    borderRadius: theme.borderRadius.lg,
    padding: theme.spacing.lg,
    boxShadow: "0 4px 20px rgba(0, 0, 0, 0.08)",
  },
  title: {
    textAlign: "center",
    color: theme.colors.primary,
    marginBottom: theme.spacing.md,
    fontSize: "clamp(1.5rem, 4vw, 2rem)",
    fontWeight: "600",
  },
  button: {
    backgroundColor: theme.colors.primary,
    color: "#ffffff",
    border: "none",
    borderRadius: theme.borderRadius.md,
    padding: "12px 24px",
    cursor: "pointer",
    fontSize: "1rem",
    fontFamily: theme.font.family,
    fontWeight: "500",
    transition: "background-color 0.2s ease",
  },
  buttonSecondary: {
    backgroundColor: theme.colors.secondary,
    color: theme.colors.primary,
    border: "1px solid " + theme.colors.border,
    borderRadius: theme.borderRadius.md,
    padding: "12px 24px",
    cursor: "pointer",
    fontSize: "1rem",
    fontFamily: theme.font.family,
    fontWeight: "500",
    transition: "background-color 0.2s ease",
  },
  buttonRow: {
    display: "flex",
    gap: theme.spacing.sm,
    flexWrap: "wrap",
    justifyContent: "center",
    marginTop: theme.spacing.md,
  },
  table: {
    width: "100%",
    borderCollapse: "collapse",
    marginTop: theme.spacing.sm,
    fontSize: "clamp(0.875rem, 2vw, 1rem)",
  },
  tableHeader: {
    backgroundColor: theme.colors.primary,
    color: "#ffffff",
    fontWeight: "600",
    padding: "14px 12px",
    border: "1px solid " + theme.colors.border,
    textAlign: "center",
  },
  tableCell: {
    padding: "12px",
    border: "1px solid " + theme.colors.border,
    textAlign: "center",
    verticalAlign: "middle",
  },
  tableRowEven: {
    backgroundColor: theme.colors.lightBlue,
  },
  input: {
    width: "100%",
    border: "1px solid " + theme.colors.border,
    borderRadius: theme.borderRadius.md,
    padding: "10px 12px",
    fontSize: "1rem",
    fontFamily: theme.font.family,
  },
  textarea: {
    width: "100%",
    border: "1px solid " + theme.colors.border,
    borderRadius: theme.borderRadius.md,
    padding: "10px 12px",
    fontSize: "1rem",
    fontFamily: theme.font.family,
    resize: "vertical",
    minHeight: "80px",
  },
  select: {
    width: "100%",
    border: "1px solid " + theme.colors.border,
    borderRadius: theme.borderRadius.md,
    padding: "10px 12px",
    fontSize: "1rem",
    fontFamily: theme.font.family,
  },
};
